### ISSUE TITLE
Remove unused code from integration tests

### ISSUE THREAD

**Issue by helayoty** [kubernetes-sigs/scheduler-plugins#325]
Most of the framework code in the integration test is not used and needs to be cleaned up

ref: https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/test/util

**Comment by Matheusafonsouza** [comment]
Hey! @helayoty can you explain this issue better for me? I'm a new contributer btw

**Comment by Huang-Wei** [comment]
The latest status is tracked at https://github.com/kubernetes-sigs/scheduler-plugins/issues/178#issuecomment-965619237 - to reuse some upstream test utilities, I had to import some testdata files, and it's crappy to hack vendoring them. So it'd be desired to (1) remove the old test utility files, along with (2) a fix to not hack vendoring those testdata files.

**Comment by Huang-Wei** [comment]
By "hack vendoring", I mean:

https://github.com/kubernetes-sigs/scheduler-plugins/blob/3a31d4a72c433b403cfc5d4815cd5b0d3b76080a/hack/integration-test.sh#L50

@Matheusafonsouza the background is that:

- in the very beginning, we copied some apiserver testing files to build out integration test
- currently the copied filed are not necessary due to the efforts in #287, however, I had to vendor some testdata files, which is a bit crappy and fragile IMO
- so although the old copied apiserver testing files can be safely deleted, I still want the testdata files can be removed. They can be altogether in one PR, or separate PRs

**Comment by Matheusafonsouza** [comment]
@Huang-Wei just a last question

So the purpose of this issue is remove all integrations tests from the scheduler-plugins? (it wont have any integration test?)
Just a doubt because i'm new in this repository

**Comment by Huang-Wei** [comment]
Nope, just remove the old and unused helper utilities. And get rid of the hack on testdata files.

**Comment by Huang-Wei** [comment]
@Matheusafonsouza @thiagompc I'd prefer to close this issue and track all needed work in #339.

/close
