### ISSUE TITLE
add e2e tests to all plugins 

### ISSUE THREAD

**Issue by helayoty** [kubernetes-sigs/scheduler-plugins#331]
It would be ideal to add e2e tests to the current plugins. This can be done by leveraging the [e2e-framework](https://github.com/kubernetes-sigs/e2e-framework) sub-project.

- [ ] e2e framework base implementation (#349 )
- [ ] tests for plugins

ref: https://github.com/Azure/placement-policy-scheduler-plugins/tree/main/test/e2e

**Comment by fromanirh** [comment]
I'm very interested in this, and I'd love to help at least for the noderesourcetopology plugin.

**Comment by helayoty** [comment]
> I'm very interested in this, and I'd love to help at least for the noderesourcetopology plugin.

Thanks, @fromanirh for that. Much needed :)
 I'm working on finalizing the first step of adding the framework in place and you'll be more than welcome to add tests for plugins then.

I'll update the issue with the PR shortly.

**Comment by helayoty** [comment]
@fromanirh  Here is the first PR. once approved, please go ahead and add tests cases for one or many plugins :)
https://github.com/kubernetes-sigs/scheduler-plugins/pull/349

**Comment by fromanirh** [comment]
thanks @helayoty and sorry for the late notice. I'll take a look ASAP

**Comment by fromanirh** [comment]
(still catching up, sorry!) for the noderesourcetopology plugin, which I'm very interested into, I'm not sure a proper e2e test is possible. The reason for me saying so is the plugin depends on data which is meant to be populated by other cluster components (node agents, daemonsets running on nodes). The problem here is that to have meaningful data, we would need 2+ worker nodes each with 2+ NUMA nodes. If this minimum requirement is not met, there's not real much value added by a e2e test over integration tests.
I'm not sure how we can move forward here, so I'm just documenting this requirement for now.
