### ISSUE TITLE
Release for Kubernetes v1.25

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/scheduler-plugins#503]
Currently, the latest released scheduler-plugins is compiled with the Kubernetes v1.24 library.
So I want the release for Kubernetes v1.25 since that is a bit old.

Does the team have release plans for Kubernetes v1.25?

If the team doesn't have enough bandwidth to create a release, I could help on a few.

cc: @Huang-Wei @denkensk

**Comment by Huang-Wei** [comment]
> Does the team have release plans for Kubernetes v1.25?

Yes, we do. Usually, we cut official releases every ~3 months, so given the last release was cut in [mid-Dec](https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.24.9), the next v0.25 would come out early March.

> So I want the release for Kubernetes v1.25 since that is a bit old.

The latest `master` is based on v1.25, which gives us some time for all dev work to soak, and also for upstream critical cherry-picks to happen. This is intentional to be a bit late than the upstream.

However, let me know if you have some critical work depending on 1.25, I can do a v1.25 pre-release.

**Comment by tenzen-y** [comment]
Thanks for letting me know! I'm fine with early March.

Thanks for your effort.

/close
