### ISSUE TITLE
We should host the helm chart on our github page

### ISSUE THREAD

**Issue by zwpaper** [kubernetes-sigs/scheduler-plugins#607]
### Area

- [ ] Scheduler
- [ ] Controller
- [X] Helm Chart
- [ ] Documents

### What happened?

users can only use the scheduler plugins Helm Chart from the source code

### What did you expect to happen?

install scheduler plugins Helm Chart directly from the internet(github page)

we can use https://github.com/helm/chart-releaser to create the release and index for the Chart,
it would:

1. create a chart artifacts to GitHub Release
2. create an `index.yaml` which we could used to hosted on GitHub Page

### Kubernetes version

<details>

```console
$ kubectl version
# 1.26.7
```

</details>

### Scheduler Plugins version

<details>
0.26.7
</details>

**Comment by Huang-Wei** [comment]
I'm not sure this is still valid: https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417. Jus FYI.

**Comment by Huang-Wei** [comment]
Seems Github pages has evolved a lot since last time I used it:

## build from source

![image](https://github.com/kubernetes-sigs/scheduler-plugins/assets/1425903/77607c2f-0c4c-4e1e-9f34-44a663661e0a)

## build from github actions

<img width="968" alt="image" src="https://github.com/kubernetes-sigs/scheduler-plugins/assets/1425903/af96017c-081c-477f-b778-c3c2d67d6c8b">

@zwpaper you can explore either option to build

**Comment by zwpaper** [comment]
GitHub Action may be a good option, we can use the markdown docs in repo to build a website.

I will look into this after I fix the 1.27 bug

**Comment by Huang-Wei** [comment]
> I will look into this after I fix the 1.27 bug

Yup, that's definitely a higher priority one.

**Comment by zwpaper** [comment]
/reopen

we should leave this issue open until host the index on out netlify page

**Comment by zwpaper** [comment]
/close 

we have hosted the chart on page
