### ISSUE TITLE
No appgroup controller and network topology controller after applying manifests/install/all-in-one.yaml

### ISSUE THREAD

**Issue by Mommment** [kubernetes-sigs/scheduler-plugins#644]
### Area

- [ ] Scheduler
- [X] Controller
- [ ] Helm Chart
- [ ] Documents

### What happened?

I'm trying to test network awareness scheduling. I applied two crds and modified all-in-one.yaml (uncomment the followling lines).
`# for network-aware plugins add the following lines (scheduler-plugins v.0.24.9)
#- apiGroups: [ "appgroup.diktyo.k8s.io" ]
#  resources: [ "appgroups" ]
#  verbs: [ "get", "list", "watch", "create", "delete", "update", "patch" ]
#- apiGroups: [ "networktopology.diktyo.k8s.io" ]
#  resources: [ "networktopologies" ]
#  verbs: [ "get", "list", "watch", "create", "delete", "update", "patch" ]`
but when I get logs of controller, there is no appgroup controller and after i applied appgroup-example and tried to get appgroups, there is no index generated for each workload.
I wanna ask if there is something I missed...

### What did you expect to happen?

in this video, [https://www.youtube.com/watch?v=E4cP275_OCs](url), after applying all-in-one file, there would be two additional controller, appgroup controller and network topology controller when checking the logs of controller pod. And when trying get appgroups, there would be an index for each workload.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}


</details>


### Scheduler Plugins version

v0.26.7

**Comment by Huang-Wei** [comment]
cc @jpedro1992

**Comment by jpedro1992** [comment]
Hi, indeed the all-in-one.yaml file does not include the appgroup and networktopology controllers since these are currently hosted outside this repo. 

You can find deployment files for these here: [appgroup](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/appgroup/deploy-appgroup-controller.yaml) and [networktopology](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/networktopology/deploy-networktopology-controller.yaml). 

These are currently deployed separately from the main scheduling controller.
