### ISSUE TITLE
Test TestCoschedulingPlugin is flaky

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#99]
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_scheduler-plugins/88/pull-scheduler-plugins-integration-test/1325299404722147328

**Comment by cwdsuzhou** [comment]
I will take a look today

**Comment by cwdsuzhou** [comment]
I found  the unit test block here

https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/test/integration/coscheduling_test.go#L376

That is because we can not ensure pod with high priority queue before the lower ones for `different priority, sequentially pg1 meet min and pg2 meet min`, pod with high priority have not enqueued (or created) at that time.

as we see
![image](https://user-images.githubusercontent.com/12230714/98623913-a6061a00-2347-11eb-99a9-c42e8c683f7f.png)

![image](https://user-images.githubusercontent.com/12230714/98624087-009f7600-2348-11eb-9d53-ea139df425e4.png)


All of them scheduled. so `numUnschedulablePods` is always 0, we wait here forever. So integration test timeout finally.
